---
Name: calendaroutes
---
Director:
  rules:
    'fullcalendar//$Action/$ID/$OtherID': 'FullcalendarController'
    'calregistrations//$Action/$ID/$OtherID': 'EventRegistrationController'
    'ics//$Action/$ID/$OtherID': 'ICSExport_Controller'
